### ISSUE TITLE
Switch password encryption from SHA1 to SHA256 (or better)

### ISSUE THREAD

**Issue by Etuldan** [Etuldan/UserNougat#2]
http://usercake.com/thread.php?id=470

**Comment by davarravad** [comment]
I did a little research a while back when I had an issue with the password hashing that was built into usercake 2.0.2.  After some research I found that php.net says to use the built in password function.

http://usercake.com/thread.php?id=778

I posted in the above thread.  May be worth looking into.

**Comment by Etuldan** [comment]
Thank you DaVaR for the explanation and the example.
As it's a possible security issue, the enhancement is done directly on master branch.
